### ISSUE TITLE
Problem with ESM 10.0

### ISSUE THREAD

**Issue by stager999** [andywalden/esm-check-ds#1]
Hi, I've tried your nice script for DS inactivity. However I have a problem that the result is empty. After debugging I've found put that my result for variable "thing" is list and not dict (dicts are within the list):
[{'id': '144116287604260864', 'name': 'Test', 'type': 'THIRD_PARTY'}, {'id': '144116287621038080', 'name': 'Correlation Engine', 'type': 'THIRD_PARTY'}, {'id': '144116287637815296', 'name': 'AD-Lab', 'type': 'THIRD_PARTY'}, {'id': '144116287654592512', 'name': 'ISIM', 'type': 'THIRD_PARTY'}, {'id': '144116287671369728', 'name': 'test1', 'type': 'THIRD_PARTY'}, {'id': '144116287688146944', 'name': 'Imperva', 'type': 'THIRD_PARTY'}, {'id': '144116287704924160', 'name': 'Imperva2', 'type': 'THIRD_PARTY'}, {'id': '144116287721701376', 'name': 'Imperva3', 'type': 'THIRD_PARTY'}, {'id': '144116287738478592', 'name': 'Imperva5', 'type': 'THIRD_PARTY'}, {'id': '144116287755255808', 'name': 'comp', 'type': 'THIRD_PARTY'}, {'id': '144116287772033024', 'name': 'TestSCP', 'type': 'THIRD_PARTY'}, {'id': '144116287788810240', 'name': 'RSA_pass', 'type': 'THIRD_PARTY'}]

After changing the script I've got also a problem with eventquery (response 400). What could be the reason for these problems?

**Comment by andywalden** [comment]
Sorry, that code wasn't meant to be working code, but an example of how the 10.x API changes impacted 9.x scripts. I've updated it now and created a blog post discussing the changes at https://community.mcafee.com/people/andy777/blog/2017/04/24/esm-api-100-updates. Thanks.
